[project]
name = "pulumi-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.6",
]

[dependency-groups]
dev = [
    "pulumi>=3.145.0",
    "pulumi-aws>=6.66.2",
]
